# Menentukan image Docker default yang akan digunakan
# Kita gunakan image yang sudah ada Java & Android SDK untuk mempermudah
default:
  image: mobiledevops/android-sdk-29-stable

# Mendefinisikan tahapan (stages) pipeline
stages:
  - test

# Mendefinisikan job yang akan dijalankan
katalon_android_test:
  stage: test # Job ini berjalan di stage 'test'
  
  # Perintah-perintah yang akan dieksekusi
  script:
    - echo "Starting Katalon Android Test..."

    # Install dependencies
    - apt-get update && apt-get install -y wget npm xvfb
    - npm install -g appium

    # Download dan install Katalon
    - wget https://github.com/katalon-studio/katalon-studio/releases/download/v8.6.5/Katalon_Studio_Engine_Linux_64-8.6.5.tar.gz
    - tar -xzf Katalon_Studio_Engine_Linux_64-8.6.5.tar.gz
    - mv Katalon_Studio_Engine_Linux_64-8.6.5 katalon

    # Jalankan tes dengan Xvfb (virtual display)
    - xvfb-run ./katalon/katalonc -projectPath="$(pwd)/Android Mobile Tests with Katalon Studio.prj" -retry=0 -testSuitePath="Test Suites/Smoke Tests for Mobile Testing" -executionProfile="default" -browserType="Mobile" -reportFolder=Reports

  # Mengatur artefak: menyimpan folder Reports agar bisa di-download
  artifacts:
    when: always
    paths:
      - Reports/