default:
  image: mobiledevops/android-sdk-29-stable

stages:
  - test

katalon_android_test:
  stage: test
  
  script:
    - echo "Starting Katalon Android Test..."
    - apt-get update && apt-get install -y wget npm xvfb
    - npm install -g appium
    - wget https://github.com/qase-tms/qase-cli/releases/latest/download/qase-linux-amd64 -O qase
    - tar -xzf Katalon_Studio_Engine_Linux_64-8.6.5.tar.gz
    - mv Katalon_Studio_Engine_Linux_64-8.6.5 katalon
    - xvfb-run ./katalon/katalonc -projectPath="$(pwd)/Android Mobile Tests with Katalon Studio.prj" -retry=0 -testSuitePath="Test Suites/Smoke Tests for Mobile Testing" -executionProfile="default" -browserType="Mobile" -reportFolder=Reports

    # === BAGIAN PELAPORAN KE QASE (SUDAH DIPERBAIKI) ===
    - |
      echo "Checking for Qase Run ID..."
      if [ -z "$QASE_RUN_ID" ]; then
        echo "This pipeline was not triggered by Qase. Skipping result upload."
      else
        echo "Uploading results to Qase Test Run ID: $QASE_RUN_ID"
        chmod +x qase
        export QASE_API_TOKEN=$QASE_API_KEY
        ./qase reporter --project-code MKQ --run-id "$QASE_RUN_ID" --path Reports/ --format junit
      fi

  artifacts:
    when: always
    paths:
      - Reports/