image: mobiledevops/android-sdk-29-stable

pipelines:
  # Pipeline ini akan berjalan saat ada push ke branch manapun
  default:
    - step:
        name: Run Katalon Android Test
        size: 2x
        script:
          - apt-get update && apt-get install -y wget npm xvfb
          - npm install -g appium
          - wget https://github.com/katalon-studio/katalon-studio/releases/download/v8.6.5/Katalon_Studio_Engine_Linux_64-8.6.5.tar.gz
          - tar -xzf Katalon_Studio_Engine_Linux_64-8.6.5.tar.gz
          - mv Katalon_Studio_Engine_Linux_64-8.6.5 katalon
          - xvfb-run ./katalon/katalonc -projectPath="$(pwd)/Android Mobile Tests with Katalon Studio.prj" -retry=0 -testSuitePath="Test Suites/Smoke Tests for Mobile Testing" -executionProfile="default" -browserType="Mobile" -reportFolder=Reports

  # Pipeline KHUSUS yang akan dipanggil oleh webhook Qase
  custom:
    qase-trigger:
      - step:
          name: Run Katalon and Report to Qase
          size: 2x
          script:
            # Langkah-langkahnya sama seperti di atas
            - apt-get update && apt-get install -y wget npm xvfb
            - npm install -g appium
            - wget https://github.com/katalon-studio/katalon-studio/releases/download/v8.6.5/Katalon_Studio_Engine_Linux_64-8.6.5.tar.gz
            - tar -xzf Katalon_Studio_Engine_Linux_64-8.6.5.tar.gz
            - mv Katalon_Studio_Engine_Linux_64-8.6.5 katalon
            - xvfb-run ./katalon/katalonc -projectPath="$(pwd)/Android Mobile Tests with Katalon Studio.prj" -retry=0 -testSuitePath="Test Suites/Smoke Tests for Mobile Testing" -executionProfile="default" -browserType="Mobile" -reportFolder=Reports

            # Bagian pelaporan ke Qase
            - wget https://github.com/qase-tms/qase-cli/releases/latest/download/qase-linux-amd64 -O qase
            - chmod +x qase
            - export QASE_API_TOKEN=$QASE_API_KEY
            - ./qase reporter --project-code MKQ --run-id "$QASE_RUN_ID" --path Reports/ --format junit --run-complete
          artifacts:
            - Reports/**