# Menentukan image Docker yang akan digunakan untuk menjalankan pipeline
image: mobiledevops/android-sdk-29-stable

pipelines:
  default:
    - step:
        name: Run Katalon Android and Report to Qase
        # Mengatur ukuran memori yang lebih besar untuk build
        size: 2x
        script:
          - apt-get update && apt-get install -y wget npm xvfb
          - npm install -g appium
          - wget https://github.com/katalon-studio/katalon-studio/releases/download/v8.6.5/Katalon_Studio_Engine_Linux_64-8.6.5.tar.gz
          - tar -xzf Katalon_Studio_Engine_Linux_64-8.6.5.tar.gz
          - mv Katalon_Studio_Engine_Linux_64-8.6.5 katalon
          - xvfb-run ./katalon/katalonc -projectPath="$(pwd)/Android Mobile Tests with Katalon Studio.prj" -retry=0 -testSuitePath="Test Suites/Smoke Tests for Mobile Testing" -executionProfile="default" -browserType="Mobile" -reportFolder=Reports
          - wget https://github.com/qase-tms/qase-cli/releases/latest/download/qase-linux-amd64 -O qase
          - chmod +x qase
          - export QASE_API_TOKEN=$QASE_API_KEY
          - ./qase reporter --project-code MKQ --run-name "Bitbucket Pipeline Run - $BITBUCKET_BUILD_NUMBER" --path Reports/ --format junit --run-complete
        artifacts:
          - Reports/**