name: Run Katalon Android Tests

on:
  workflow_dispatch:   # Bisa dijalankan manual dari GitHub
  repository_dispatch: # Bisa ditrigger Qase lewat API

jobs:
  katalon_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK and Emulator
        run: |
          export ANDROID_HOME=/usr/local/lib/android/sdk
          sudo mkdir -p $ANDROID_HOME/cmdline-tools
          sudo chown $USER:$USER $ANDROID_HOME/cmdline-tools
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools/tmp
          mv $ANDROID_HOME/cmdline-tools/tmp/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          rm -rf $ANDROID_HOME/cmdline-tools/tmp

          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0" "system-images;android-33;google_apis;x86_64" "emulator"

      - name: Create and Start Emulator
        run: |
          echo no | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-33;google_apis;x86_64" --force
          $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio -no-snapshot &
          adb wait-for-device
          adb shell input keyevent 82
          sleep 10

      - name: Install Appium
        run: npm install -g appium

      - name: Install Katalon
        run: |
          wget https://github.com/katalon-studio/katalon-studio/releases/download/v8.6.5/Katalon_Studio_Engine_Linux_64-8.6.5.tar.gz
          tar -xvzf Katalon_Studio_Engine_Linux_64-8.6.5.tar.gz
          mv Katalon_Studio_Engine_Linux_64-8.6.5 katalon

      - name: Run Katalon Android Tests
        run: |
          ./katalon/katalonc \
            -projectPath="$(pwd)/Android Mobile Tests with Katalon Studio.prj" \
            -retry=0 \
            -testSuitePath="Test Suites/Smoke Tests for Mobile Testing" \
            -executionProfile="default" \
            -browserType="Mobile"

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: katalon-report
          path: Reports/**

      - name: Push results to Qase (dummy)
        run: |
          curl -X POST "https://api.qase.io/v1/result/MKQ" \
          -H "Token: ${{ secrets.QASE_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"status": "passed"}'
