name: Run Katalon Android Tests

on:
  workflow_dispatch:

jobs:
  katalon_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          emulator-boot-timeout: 600
          script: |
            adb shell settings put global window_animation_scale 0
            adb shell settings put global transition_animation_scale 0
            adb shell settings put global animator_duration_scale 0
            adb shell input keyevent 82

      - name: Install Appium
        run: npm install -g appium

      - name: Install Katalon
        run: |
          wget https://github.com/katalon-studio/katalon-studio/releases/download/v8.6.5/Katalon_Studio_Engine_Linux_64-8.6.5.tar.gz
          tar -xvzf Katalon_Studio_Engine_Linux_64-8.6.5.tar.gz
          mv Katalon_Studio_Engine_Linux_64-8.6.5 katalon
      
      - name: Start virtual display
        uses: GabrielBB/xvfb-action@v1

      - name: Run Katalon Android Tests
        run: |
          ./katalon/katalonc \
            -projectPath="$(pwd)/Android Mobile Tests with Katalon Studio.prj" \
            -retry=0 \
            -testSuitePath="Test Suites/Smoke Tests for Mobile Testing" \
            -executionProfile="default" \
            -browserType="Mobile" \
            -reportFolder=Reports # Ensure report is generated here

      # (Optional) You can keep this step to upload the raw report as an artifact
      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: katalon-report
          path: Reports/

      # ✅ CORRECTED STEP: Publish test results to Qase
      - name: Publish to Qase
        if: always() # This ensures results are published even if tests fail
        uses: qase-tms/qase-github-reporter@v2
        with:
          # Your Qase API token secret
          api-token: ${{ secrets.QASE_API_KEY }}

          # Your Qase project code
          project-code: 'MKQ'

          # The format of the report Katalon generates
          reporter: junit

          # The path to the XML report file. 
          # Katalon usually puts it in a sub-folder inside Reports.
          path: 'Reports/**/*.xml'
          
          # This creates a new run with a useful name
          run-name: 'Android Test Run via GitHub Actions'
          run-complete: true