name: Run Katalon and Report via Qase CLI

on:
  workflow_dispatch:
    inputs:
      qase_run_id:
        description: 'Qase Run ID to update'
        required: false
  repository_dispatch:

jobs:
  katalon_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          emulator-boot-timeout: 600
          script: |
            adb shell settings put global window_animation_scale 0
            adb shell settings put global transition_animation_scale 0
            adb shell settings put global animator_duration_scale 0
            adb shell input keyevent 82

      - name: Install Appium
        run: npm install -g appium

      - name: Install Katalon
        run: |
          wget https://github.com/katalon-studio/katalon-studio/releases/download/v8.6.5/Katalon_Studio_Engine_Linux_64-8.6.5.tar.gz
          tar -xvzf Katalon_Studio_Engine_Linux_64-8.6.5.tar.gz
          mv Katalon_Studio_Engine_Linux_64-8.6.5 katalon
      
      - name: Start virtual display
        uses: GabrielBB/xvfb-action@v1

      - name: Run Katalon Android Tests
        run: |
          ./katalon/katalonc \
            -projectPath="$(pwd)/Android Mobile Tests with Katalon Studio.prj" \
            -retry=0 \
            -testSuitePath="Test Suites/Smoke Tests for Mobile Testing" \
            -executionProfile="default" \
            -browserType="Mobile" \
            -reportFolder=Reports

      - name: Publish to Qase using Qase CLI
        if: always()
        run: |
          # Dapatkan Run ID yang dikirim dari Qase
          QASE_RUN_ID="${{ github.event.client_payload.qase_run_id || github.event.inputs.qase_run_id }}"

          # Hanya jalankan jika Run ID ada (artinya ditrigger dari Qase)
          if [ -z "$QASE_RUN_ID" ]; then
            echo "Qase Run ID not provided. Skipping result upload."
          else
            echo "Uploading results to Qase Test Run ID: $QASE_RUN_ID"
            
            # Download Qase CLI
            wget https://github.com/qase-tms/qase-cli/releases/latest/download/qase-linux-amd64 -O qase
            chmod +x qase

            # Jalankan Qase CLI untuk mengunggah report dari folder Reports
            ./qase reporter --project-code MKQ --run-id "$QASE_RUN_ID" --path Reports/ --format junit
          fi
        env:
          # Pastikan nama secret Anda adalah QASE_API_KEY
          QASE_API_TOKEN: ${{ secrets.QASE_API_KEY }}